version: '3.8'
services:
  db:
    image: postgres:14
    container_name: db_container
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 5
    restart: on-failure
    volumes:
      - postgresql_volume_compose:/var/lib/postgresql/data
      - ./etl/etl/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "${PORT_DB}:${PORT_DB}"

  movies_admin:
    build:
      context: ./movies_admin/movies_admin
    volumes:
      - static_volume:/home/app/movies_admin/staticfiles
      - media_volume:/home/app/movies_admin/mediafiles
    depends_on:
      db:
        condition: service_healthy
    container_name: movies_admin_container
    restart: unless-stopped
    env_file:
      - ./.env

  nginx:
    image: nginx:1.22.1
    container_name: nginx_container
    volumes:
      - static_volume:/home/app/movies_admin/staticfiles
      - media_volume:/home/app/movies_admin/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - movies_admin
    restart: always

  redis:
    image: redis:7.0.7
    container_name: redis_container
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - redis_volume:/data
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"

  elastic:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - USE_SSL=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9200 | grep -q 'HTTP/1.1 200 OK'",
        ]
      interval: 1s
      timeout: 5s
      retries: 120
    container_name: elastic_compose
    ports:
      - "${PORT_ELASTIC}:${PORT_ELASTIC}"
    volumes:
      - elastic_volume_compose:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=["http://elastic:9200"]
    ports:
      - "${PORT_KIBANA}:${PORT_KIBANA}"
    container_name: kibana_compose
    volumes:
      - kibana_volume_compose:/usr/share/kibana/data
    depends_on:
      elastic:
        condition: service_healthy
    restart: unless-stopped

  etl:
    build:
      context: ./etl/etl
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy
      elastic:
        condition: service_healthy
    container_name: etl_container
    restart: unless-stopped

  fastapi:
    build:
      context: ./fastapi
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elastic:
        condition: service_healthy
    container_name: fastapi_container
    restart: unless-stopped
    ports:
      - "${PORT_FASTAPI}:${PORT_FASTAPI}"

volumes:
  static_volume:
  media_volume:
  postgresql_volume_compose:
  redis_volume:
  elastic_volume_compose:
  kibana_volume_compose:
